# Esempio file /etc/pve/lxc/<ID>.conf per Nextcloud + Docker


arch: amd64
cores: 8
hostname: nextcloud-server
memory: 16384
swap: 8192
onboot: 1
ostype: debian
rootfs: tank:subvol-121-disk-0,size=500G
net0: name=eth0,bridge=vmbr0,gw=192.168.1.1,hwaddr=BC:24:11:BB:DF:3B,ip=192.168.1.80/24


# Abilita Docker dentro LXC
features: nesting=1,keyctl=1

# Permessi estesi per Docker e Pi-hole (DNS, mount, ecc.)
lxc.cgroup2.devices.allow: a


# Note:
# - Il numero del container è ID:121
# - Per la memorizzazione dei dati utilizziamo in proxmox un disco di tipo ZFS di nome: tank
# - unprivileged=1 permette maggiore sicurezza per LXC
# - nesting=1 è obbligatorio per docker dentro container
