# Esempio file /etc/pve/lxc/<ID>.conf per Nextcloud + Docker


arch: amd64
cores: 8
hostname: nextcloud-server
memory: 16384
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,hwaddr=BC:24:11:BB:DF:3B,ip=192.168.1.80/24,type=veth
ostype: alpine
rootfs: tank:subvol-121-disk-0,size=500G
swap: 512
unprivileged: 1
onboot: 1

features: nesting=1
lxc.cap.keep: CAP_NET_BIND_SERVICE
lxc.apparmor.profile: unconfined
lxc.cap.drop:

# Note:
# - Il numero del container è ID:121
# - Per la memorizzazione dei dati utilizziamo in proxmox un disco di tipo ZFS di nome: tank
# - unprivileged=1 permette maggiore sicurezza per LXC
# - nesting=1 è obbligatorio per docker dentro container
